from ic_marathon_app.models import Profile
from django.core.exceptions import MultipleObjectsReturned
from ic_marathon_app.views import check_badges

cecs_who_joined = [
   "alegarc2",
"guamarti",
"lramosba",
"alberthe",
"baraiza",
"jacbeltr",
"alsalvad",
"afariasd",
"gerestra",
"migserra",
"josgonz5",
"jdavilad",
"mariacv2",
"sarifern",
"alzavala",
"amarana",
"flugo",
"hrizkcab",
"apucheta",
"oscblanc",
"romcleme",
"vbustama",
"maydomin",
"lucervan",
"martvazq",
"moacosta",
"caguille",
"gdiazsan",
"vgilguzm",
"alesalga",
"fchongce",
"alfespin",
"antonma2",
"jfarellb",
"cadiazar",
"marintor",
"colmedo",
"rrendonm",
"jgomezsu",
"olopezcr",
"saurodri",
"ebellogo",
"gubell",
"marjuare",
"bzendeja",
"omchavar",
"edescala",
"drincond",
"jviniegr",
"espachec",
"mancabre",
"frangon3",
"iowen",
"luicarri",
"beguerre",
"carlvarg",
"issferna",
"rutguzma",
"kagodine",
"ovicente",
"mmalacar",
"szaldiva",
"cerosale",
"davicast",
"katyator",
"manuelre",
"maespond",
"victogut",
"jamillan",
"hdiaziba",
"vpinacas",
"edusalga",
"gespinos",
"jcraviot",
"lchavezg",
"mancovar",
"blopezde",
"julhered",
"ibarraga",
"odelgado",
"avercor",
"dreyesmo",
"egomezsa",
"jquirozc",
"mgonzal4",
"nalbacas",
"omarquin",
]

for cec in cecs_who_joined:
    try:
        #get profile
        profile = Profile.objects.get(cec=cec)
        profile.distance += 5
        profile.save()
        print(f"user {cec} has been granted the gift")
        check_badges(profile.user)
    except MultipleObjectsReturned:
        #check profile manually
        print(f"duplicated user {cec}, check manually")
    except Profile.DoesNotExist:
        pass