# Generated by Django 4.2.7 on 2025-08-05 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ic_marathon_app.validators
import ic_marathon_site.storage_backends
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Intensity Level',
                'verbose_name_plural': 'Intensity Levels',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_goal', models.BooleanField(default=False)),
                ('user_goal_km', models.DecimalField(decimal_places=2, default=42.0, max_digits=10, validators=[ic_marathon_app.validators.validate_min_goal])),
                ('avatar', models.CharField(max_length=400)),
                ('cec', models.CharField(blank=True, max_length=30, validators=[ic_marathon_app.validators.validate_cec])),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Runner'), ('freestyler', 'Freestyler')], default='beginnerrunner', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[ic_marathon_app.validators.validate_distance], verbose_name='KM')),
                ('photo_evidence', models.ImageField(storage=ic_marathon_site.storage_backends.PrivateMediaStorage(), upload_to='', validators=[ic_marathon_app.validators.validate_file_size], verbose_name='Evidence')),
                ('date_time', models.DateTimeField(verbose_name='Date')),
                ('time', models.TimeField(default='00:00', help_text='Workout/Gift', verbose_name='Type')),
                ('is_audited', models.BooleanField(default=False, help_text='Already audited?', verbose_name='Audited?')),
                ('is_gift', models.BooleanField(default=False, help_text='Was this a gift (extra kms)?', verbose_name='Gift?')),
                ('belongs_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.profile')),
                ('intensity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.intensitylevel')),
                ('sport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.sport')),
            ],
        ),
        migrations.CreateModel(
            name='SportIntensityMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_per_hour', models.FloatField(help_text='Kilometers equivalent for 1 hour at this intensity.')),
                ('intensity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.intensitylevel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.sport')),
            ],
            options={
                'verbose_name': 'Sport Intensity Mapping',
                'verbose_name_plural': 'Sport Intensity Mappings',
                'unique_together': {('sport', 'intensity')},
            },
        ),
    ]
