# Generated by Django 4.2.7 on 2025-10-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0002_add_initial_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.ForeignKey(default='Light', on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.intensitylevel'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sport',
            field=models.ForeignKey(default='Running', on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.sport'),
        ),
    ]
