# Generated by Django 4.2.7 on 2025-10-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0003_alter_workout_intensity_alter_workout_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='edition',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.intensitylevel'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.sport'),
        ),
    ]
