# Generated by Django 4.2.7 on 2025-10-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0004_workout_edition_alter_workout_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, default='https://ciscorunning2023.s3.us-east-1.amazonaws.com/static/img/user.png', max_length=400),
        ),
    ]
