# Generated by Django 4.2.7 on 2025-10-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category_changed',
            field=models.BooleanField(default=False, help_text='Has the user changed their category from the default?'),
        ),
    ]
