# Generated by Django 4.2.7 on 2025-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0006_profile_category_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days with workouts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_workout_date',
            field=models.DateField(blank=True, help_text='Date of first workout - used for auto-promotion', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest streak of consecutive workout days achieved'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workout_days_count',
            field=models.IntegerField(default=0, help_text='Number of unique days with workouts - used for auto-promotion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Runner'), ('freestyler', 'Freestyler'), ('beginnerfreestyler', 'Beginner Freestyler')], default='beginnerrunner', max_length=20),
        ),
    ]
