# Generated by Django 4.2.7 on 2025-11-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0008_update_sport_intensity_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensitylevel',
            name='name',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, unique=True),
        ),
    ]
