# Generated by Django 4.2.7 on 2025-11-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0009_alter_intensitylevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='base_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original distance before 1.5x partner bonus', max_digits=5, verbose_name='Base Distance (before bonus)'),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_partner_workout',
            field=models.BooleanField(default=False, help_text='Is this a partner workout (1.5x distance bonus)?', verbose_name='Partner Workout?'),
        ),
        migrations.AddField(
            model_name='workout',
            name='partner_confirmed',
            field=models.BooleanField(default=False, help_text='Has the partner confirmed this workout?', verbose_name='Partner Confirmed?'),
        ),
        migrations.AddField(
            model_name='workout',
            name='partner_profile',
            field=models.ForeignKey(blank=True, help_text='The partner who trained with you', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_workouts_received', to='ic_marathon_app.profile'),
        ),
        migrations.AddField(
            model_name='workout',
            name='partner_workout_group',
            field=models.UUIDField(blank=True, editable=False, help_text='Shared UUID linking both partner workouts together', null=True),
        ),
    ]
