# Generated by Django 4.2.7 on 2025-12-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0010_add_partner_workout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promotion_reason',
            field=models.CharField(blank=True, help_text='Reason for auto-promotion (Path 1, 2, or 3)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Advanced Runner'), ('freestyler', 'Advanced Freestyler'), ('beginnerfreestyler', 'Beginner Freestyler')], default='beginnerrunner', max_length=20),
        ),
    ]
