# Generated by Django 2.2.13 on 2021-11-17 18:05

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0010_auto_20201101_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Runner'), ('biker', 'Biker'), ('duathloner', 'Duathloner'), ('freestyler', 'Freestyler')], default='beginnerrunner', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[ic_marathon_app.validators.validate_distance], verbose_name='KM'),
        ),
    ]
