# Generated by Django 2.2.13 on 2021-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0011_auto_20211117_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_goal_km',
            field=models.DecimalField(decimal_places=2, default=42.0, max_digits=10),
        ),
    ]
