# Generated by Django 2.2.13 on 2021-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0012_profile_user_goal_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
