# Generated by Django 2.2.13 on 2021-12-01 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0014_auto_20211117_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(models.DecimalField(verbose_name='21.0'))]),
        ),
    ]
