# Generated by Django 2.2.13 on 2021-12-01 19:45

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0016_auto_20211201_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_goal_km',
            field=models.DecimalField(decimal_places=2, default=42.0, max_digits=10, validators=[ic_marathon_app.validators.validate_min_goal]),
        ),
    ]
