# Generated by Django 4.2.7 on 2024-11-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0017_auto_20211201_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='audited',
            field=models.BooleanField(default=False, help_text='Already audited?', verbose_name='Audited?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('beginnerrunner', 'Beginner Runner'), ('runner', 'Runner'), ('biker', 'Biker'), ('duathloner', 'Duathloner'), ('freestyler', 'Freestyler'), ('advfreestyler', 'Advanced Freestyler')], default='beginnerrunner', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10, verbose_name='Intensity'),
        ),
    ]
