# Generated by Django 4.2.7 on 2024-11-22 16:50

from django.db import migrations, models
import ic_marathon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0018_workout_audited_alter_profile_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='audited',
            new_name='is_audited',
        ),
        migrations.AddField(
            model_name='workout',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Was this a gift (extra kms)?', verbose_name='Gift?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cec',
            field=models.CharField(blank=True, max_length=30, validators=[ic_marathon_app.validators.validate_cec]),
        ),
    ]
