# Generated by Django 4.2.7 on 2025-08-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_marathon_app', '0020_alter_profile_category_alter_workout_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Intensity Level',
                'verbose_name_plural': 'Intensity Levels',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.sport'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.intensitylevel'),
        ),
        migrations.CreateModel(
            name='SportIntensityMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_per_hour', models.FloatField(help_text='Kilometers equivalent for 1 hour at this intensity.')),
                ('intensity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.intensitylevel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_marathon_app.sport')),
            ],
            options={
                'verbose_name': 'Sport Intensity Mapping',
                'verbose_name_plural': 'Sport Intensity Mappings',
                'unique_together': {('sport', 'intensity')},
            },
        ),
    ]
